"""updateClient_donation_time

Revision ID: a65eedaef175
Revises: fd9436991998
Create Date: 2024-04-22 03:13:13.488501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65eedaef175'
down_revision: Union[str, None] = 'fd9436991998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('next_donation_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'next_donation_time')
    # ### end Alembic commands ###
